package coffeshop.com.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BilldetailId generated by hbm2java
 */
@Embeddable
public class BilldetailId implements java.io.Serializable {

	private int productid;
	private int billid;

	public BilldetailId() {
	}

	public BilldetailId(int productid, int billid) {
		this.productid = productid;
		this.billid = billid;
	}

	@Column(name = "PRODUCTID", nullable = false, length = 7)
	public int getProductid() {
		return this.productid;
	}

	public void setProductid(int productid) {
		this.productid = productid;
	}

	@Column(name = "BILLID", nullable = false)
	public int getBillid() {
		return this.billid;
	}

	public void setBillid(int billid) {
		this.billid = billid;
	}



}
