package coffeshop.com.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BooktableId generated by hbm2java
 */
@Embeddable
public class BooktableId implements java.io.Serializable {

	private int customerid;
	private int dinnertableid;
	private int employeeid;

	public BooktableId() {
	}

	public BooktableId(int customerid, int dinnertableid, int employeeid) {
		this.customerid = customerid;
		this.dinnertableid = dinnertableid;
		this.employeeid = employeeid;
	}

	@Column(name = "CUSTOMERID", nullable = false)
	public int getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(int customerid) {
		this.customerid = customerid;
	}

	@Column(name = "DINNERTABLEID", nullable = false)
	public int getDinnertableid() {
		return this.dinnertableid;
	}

	public void setDinnertableid(int dinnertableid) {
		this.dinnertableid = dinnertableid;
	}

	@Column(name = "EMPLOYEEID", nullable = false, length = 7)
	public int getEmployeeid() {
		return this.employeeid;
	}

	public void setEmployeeid(int employeeid) {
		this.employeeid = employeeid;
	}



}
