package coffeshop.com.entity;
// Generated Nov 20, 2018 8:44:18 AM by Hibernate Tools 5.1.7.Final

import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "schedule", catalog = "cafeshop")
public class Schedule implements java.io.Serializable {
	@Id
	@Column(name = "SCHEDULEID", unique = true, nullable = false, length = 7)
	private int scheduleid;

	@Column(name = "NAME")
	private String name;

	@Temporal(TemporalType.TIME)
	@Column(name = "STARTTIME", length = 8)
	private Date starttime;

	@Temporal(TemporalType.TIME)
	@Column(name = "ENDTIME", length = 8)
	private Date endtime;

	@Column(name = "PAYRATE", precision = 12, scale = 0)
	private Float payrate;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "UPDATEAT", length = 19)
	private Date updateat;

	@Column(name = "ISDELETE")
	private Boolean isdelete;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "schedule")
	private Set<Register> registers = new HashSet<Register>(0);

	public Schedule() {
	}


	public int getScheduleid() {
		return scheduleid;
	}

	public void setScheduleid(int scheduleid) {
		this.scheduleid = scheduleid;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}


	public Float getPayrate() {
		return this.payrate;
	}

	public void setPayrate(Float payrate) {
		this.payrate = payrate;
	}

	public Date getUpdateat() {
		return this.updateat;
	}

	public void setUpdateat(Date updateat) {
		this.updateat = updateat;
	}

	public Boolean getIsdelete() {
		return this.isdelete;
	}

	public void setIsdelete(Boolean isdelete) {
		this.isdelete = isdelete;
	}

	public Set<Register> getRegisters() {
		return this.registers;
	}

	public void setRegisters(Set<Register> registers) {
		this.registers = registers;
	}

}
